[build]
    base = "Sample-01"
    command = "printf '{\"domain\":\"%s\", \"clientId\":\"%s\"}' \"${AUTH0_DOMAIN}\" \"${AUTH0_CLIENT_ID}\" > src/auth_config.json && yarn install && yarn run build"
    publish = "build"
